#!/usr/bin/env ruby
require 'rubygems'
require 'bundler'

Bundler.require

require './base'

Functions = %w(reflection full_adder counter1n quit)

def usage
  if ARGV.length < 2
    puts <<-USAGE
      USAGE: 
      generate #{Functions.join(' | ')} #Variables {complete}

      Ex: generate full_adder 4
    USAGE
    exit
  end
end

usage
yaml = Base::Specification.generate(ARGV[0], 3, ARGV[1].to_i)
if ARGV[2] == 'complete'
  yaml = Base::Transformers::Bijector.new(yaml).complete
end

puts yaml

